submitit INFO (2025-02-04 09:00:03,799) - Starting with JobEnvironment(job_id=1343577, hostname=arbeitsrechner, local_rank=0(1), node=0(1), global_rank=0(1))
submitit INFO (2025-02-04 09:00:03,799) - Loading pickle: /home/s3811141/repos/OmniOpt/ax/runs/test_wronggoing_stuff/0/single_runs/1343577/1343577_submitted.pkl
Error at execution of your program: ./.tests/test_wronggoing_stuff.bin/bin/python_name_error. Exit-Code: 1, Signal-Code: None
No stdout
stderr: Traceback (most recent call last):
  File "/home/s3811141/repos/OmniOpt/ax/./.tests/test_wronggoing_stuff.bin/bin/python_name_error", line 2, in <module>
    askldasdasd
NameError: name 'askldasdasd' is not defined

Parameters: {"program": "python_name_error"}
Debug-Infos: 
========
DEBUG INFOS START:
Program-Code: ./.tests/test_wronggoing_stuff.bin/bin/python_name_error
pwd: /home/s3811141/repos/OmniOpt/ax
File: ./.tests/test_wronggoing_stuff.bin/bin/python_name_error
UID: 1000
GID: 1000
Status-Change-Time: 1710134182.2937162
Size: 30 Bytes
Permissions: -rwxr-xr-x
Owner: s3811141
Last access: 1738651829.0453262
Last modification: 1710134182.2937162
Hostname: arbeitsrechner
========
DEBUG INFOS END

./.tests/test_wronggoing_stuff.bin/bin/python_name_error
stdout was empty
stderr: Traceback (most recent call last):
  File "/home/s3811141/repos/OmniOpt/ax/./.tests/test_wronggoing_stuff.bin/bin/python_name_error", line 2, in <module>
    askldasdasd
NameError: name 'askldasdasd' is not defined

Result: None
EXIT_CODE: 1
submitit INFO (2025-02-04 09:00:06,754) - Job completed successfully
submitit INFO (2025-02-04 09:00:06,754) - Exiting after successful completion
