submitit ERROR (2025-02-03 08:14:18,810) - Submitted job triggered an exception
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/s3811141/.omniax_x86_64_Python_3.13.1/lib/python3.13/site-packages/submitit/core/_submit.py", line 11, in <module>
    submitit_main()
    ~~~~~~~~~~~~~^^
  File "/home/s3811141/.omniax_x86_64_Python_3.13.1/lib/python3.13/site-packages/submitit/core/submission.py", line 76, in submitit_main
    process_job(args.folder)
    ~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/s3811141/.omniax_x86_64_Python_3.13.1/lib/python3.13/site-packages/submitit/core/submission.py", line 69, in process_job
    raise error
  File "/home/s3811141/.omniax_x86_64_Python_3.13.1/lib/python3.13/site-packages/submitit/core/submission.py", line 55, in process_job
    result = delayed.result()
  File "/home/s3811141/.omniax_x86_64_Python_3.13.1/lib/python3.13/site-packages/submitit/core/utils.py", line 137, in result
    self._result = self.function(*self.args, **self.kwargs)
                   ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(__main__.evaluate) at 0x7fc564307ec0>", line 31, in evaluate
  File "/home/s3811141/repos/OmniOpt/ax/.omniopt.py", line 2378, in evaluate
    write_job_infos_csv(parameters, stdout, program_string_with_params, exit_code, _signal, result, start_time, end_time, run_time)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(__main__.write_job_infos_csv) at 0x7fc564307e20>", line 176, in write_job_infos_csv
beartype.roar.BeartypeCallHintParamViolation: Function __main__.write_job_infos_csv() parameter start_time=1738566858 violates type hint <class 'float'>, as int 1738566858 not instance of float.
